// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbrogahrwyeglraesmhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJicm9nYWhyd3llZ2xyYWVzbWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzU4MjEsImV4cCI6MjA3MzAxMTgyMX0.0D1pCnUuJXgddebJ0_iU4pXZ8lzT7qoyZUvll_T8LIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});